baseURL = "/"
title = "Client Blog"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[languages]
  [languages.en]
    weight = 1
    languageName = "English"
    title = "Client Blog"
  [languages.fr]
    weight = 2
    languageName = "Français"
    title = "Blog Client"

[build]
  writeStats = true
theme = "papermod"

[params]
ShowCodeCopyButtons = true
  [params.homeInfoParams]
  Title = "Welcome to the Site"
  Content = "This is the home page. You can customize this text or remove it completely."

[module]
  [module.hugoVersion]
    extended = true
    min = "0.114.0"
